name: Use Private Action
description: Checks out a private action via token, stores it, and runs it. Dont follow with another checkout,
inputs:
  token:
    description: Token to use to get access to the private repo
    required: true
  repo:
    description: Private repo name e.g. "example/private-action"
    required: true
  ref:
    description: Ref for private action version
    required: true
  json-inputs:
    description: Json object of `inputs` to pass to private action
    required: false
    default: "{}"
  json-env:
    description: Json object of `env` to pass to private action
    required: false
    default: "{}"
  path:
    description: Where to store the private action under `$GITHUB_WORKSPACE`
    required: false
    default: "./.github/actions/private-actions/"
outputs:
  json-outputs:
    description: Json object of `outputs` from private action
    value: ${{ toJSON(steps.private-action.outputs) }}
runs:
  using: composite
  steps:
    - name: Checkout private action
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
    - name: Get paths
      id: get-paths
      shell: bash
      run: |
        echo "::workflow-command starting-path=::$(pwd)"
        echo "::workflow-command action-path=::./${{inputs.path}}/${{inputs.repo}}"
    - name: CD to action
      shell: bash
      run: |
        cd ${{ steps.echo-stuff.outputs.action-path}}
    - name: Run Private Action ${{ inputs.repo }}@${{ inputs.ref }}
      needs:
      id: private-action
      uses: ./
      env: ${{ fromJSON(inputs.json-env) }}
      with: ${{ fromJSON(inputs.json-inputs) }}
    - name: CD to starting point
      shell: bash
      run: |
        cd ${{ steps.echo-stuff.outputs.starting-path}}
